# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-efs-backup
  description: Terraform module designed to easily backup EFS filesystems to S3 using DataPipeline
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-modules, datapipeline, aws, s3, efs, nfs, backup, snapshot, lambda, automatic, scheduled-job, cronjob



