---
AWSTemplateFormatVersion: 2010-09-09
Description: DataPipeline MongoDB Backup DataPipeline Template

Parameters:
  myS3BackupsBucket:
    Type: String
  mySecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
  mySubnetId:
    Type: AWS::EC2::Subnet::Id
  myInstanceType:
    Type: String
  myMongoHost:
    Type: String
  myDBuser:
    Type: String
  myDBpassword:
    Type: String
  myDBname:
    Type: String
  myDBcollection:
    Type: String
  myDBquery:
    Type: String
  myDBatlasShared:
    Type: String
  myDBatlasReplicaset:
    Type: String
  myRegion:
    Type: String
  myImageId:
    Type: AWS::EC2::Image::Id
  myTopicArn:
    Type: String
  myS3LogBucket:
    Type: String
  myDataPipelineResourceRole:
    Type: String
  myDataPipelineRole:
    Type: String
  myKeyPair:
    Type: AWS::EC2::KeyPair::KeyName
  Tag:
    Type: String
  myPeriod:
    Type: String
  myStartDateTime:
    Type: String
  myExecutionTimeout:
    Type: String


Resources:
  DataPipelineMongoBackup:
    Type: AWS::DataPipeline::Pipeline
    Properties:
      Name: DataPipelineMongoBackup
      Description: DataPipeline MongoDB Backup
      PipelineTags:
        - Key: Name
          Value: !Ref Tag
      PipelineObjects:
        - Id: Default
          Name: Default
          Fields:
            - Key: type
              StringValue: Default
            - Key: scheduleType
              StringValue: cron
            - Key: failureAndRerunMode
              StringValue: CASCADE
            - Key: schedule
              RefValue: DefaultSchedule
            - Key: role
              StringValue: "#{myDataPipelineRole}"
            - Key: resourceRole
              StringValue: "#{myDataPipelineResourceRole}"
            - Key: pipelineLogUri
              StringValue: "#{myS3LogBucket}"
        - Id: EC2ResourceObj
          Name: EC2ResourceObj
          Fields:
            - Key: type
              StringValue: Ec2Resource
            - Key: terminateAfter
              StringValue: "#{myExecutionTimeout}"
            - Key: instanceType
              StringValue: "#{myInstanceType}"
            - Key: securityGroupIds
              StringValue: "#{mySecurityGroupId}"
            - Key: subnetId
              StringValue: "#{mySubnetId}"
            - Key: associatePublicIpAddress
              StringValue: "true"
            - Key: imageId
              StringValue: "#{myImageId}"
            - Key: keyPair
              StringValue: "#{myKeyPair}"
        - Id: DefaultSchedule
          Name: DefaultSchedule
          Fields:
            - Key: type
              StringValue: Schedule
            - Key: startDateTime
              StringValue: "#{myStartDateTime}"
            - Key: period
              StringValue: "#{myPeriod}"
        - Id: ShellCommandActivityObj
          Name: ShellCommandActivityObj
          Fields:
            - Key: type
              StringValue: ShellCommandActivity
            - Key: runsOn
              RefValue: EC2ResourceObj
            - Key: command
              StringValue: |
                source="$1"
                region="$2"
                destination="$3"
                user="$4"
                password="$5"
                dbname="$6"
                dbcollection="$7"
                query="$8"
                atlas_shared="$9"
                atlas_replicaset="$10"
                [[ -d /backup-partial ]] || sudo mkdir /backup
                if [ $atlas_shared = "true" ] || [ $atlas_replicaset = "true" ]; then
                 sudo yum-config-manager --add-repo https://repo.mongodb.org/yum/amazon/2013.03/mongodb-org/3.6/x86_64/
                 sudo rpm --import https://www.mongodb.org/static/pgp/server-3.6.asc
                 sudo yum -y install mongodb-org-tools
                else
                 sudo yum-config-manager --add-repo https://repo.mongodb.org/yum/amazon/2013.03/mongodb-org/3.2/x86_64/
                 sudo rpm --import https://www.mongodb.org/static/pgp/server-3.2.asc
                 sudo yum -y install mongodb-org-tools
                fi
                if [ $atlas_shared = "true" ]; then
                 # if [[ (-n $dbname) -a (-n $dbcollection) -a (-n $query) ]]; then
                 if [ $dbname != "none" ] || [ $dbcollection != "none" ] || [ $query != "none" ]; then
                   # Do partial backup
                   sudo mongodump -h $source:27016 -u $user -p $password --authenticationDatabase admin -d $dbname -c $dbcollection -q $query -o /backup/ --ssl
                 else
                   # Do full backup
                   sudo mongodump -h $source:27016 -u $user -p $password -o /backup/ --ssl
                 fi
                elif [ $atlas_replicaset = "true" ]; then
                 if [ $dbname != "none" ] || [ $dbcollection != "none" ] || [ $query != "none" ]; then
                   # Do partial backup
                   sudo mongodump -h $source:27017 -u $user -p $password --authenticationDatabase admin -d $dbname -c $dbcollection -q $query -o /backup/ --ssl
                 else
                   # Do full backup
                   sudo mongodump -h $source:27017 -u $user -p $password -o /backup/ --ssl
                 fi
                else
                 # if [[ (-n $dbname) -a (-n $dbcollection) -a (-n $query) ]]; then
                 if [ $dbname != "none" ] || [ $dbcollection != "none" ] || [ $query != "none" ]; then
                   # Do partial backup
                   sudo mongodump -h $source:27017 -u $user -p $password --authenticationDatabase admin -d $dbname -c $dbcollection -q $query -o /backup/
                 else
                   # Do full backup
                   sudo mongodump -h $source:27017 -u $user -p $password -o /backup/
                 fi
                fi
                sudo aws s3 sync --delete --exact-timestamps /backup/ s3://$destination/
                backup_status="$?"
                # Return code 2 means that the following were skipped:
                # files/symlinks that do not exist, files that are character special devices, block special device, FIFO's, or sockets, and files that the user cannot read from
                # We need to return 0 in this case for the pipeline to succeed because all normal files were synched successfully
                # http://docs.aws.amazon.com/cli/latest/topic/return-codes.html
                # https://github.com/aws/aws-cli/issues/1125
                if [ "$backup_status" -eq "2" ]; then
                  backup_status="0"
                fi
                exit "$backup_status"
            - Key: scriptArgument
              StringValue: "#{myMongoHost}"
            - Key: scriptArgument
              StringValue: "#{myRegion}"
            - Key: scriptArgument
              StringValue: "#{myS3BackupsBucket}"
            - Key: scriptArgument
              StringValue: "#{myDBuser}"
            - Key: scriptArgument
              StringValue: "#{myDBpassword}"
            - Key: scriptArgument
              StringValue: "#{myDBname}"
            - Key: scriptArgument
              StringValue: "#{myDBcollection}"
            - Key: scriptArgument
              StringValue: "#{myDBquery}"
            - Key: scriptArgument
              StringValue: "#{myDBatlasShared}"
            - Key: scriptArgument
              StringValue: "#{myDBatlasReplicaset}"
            - Key: onSuccess
              RefValue: SuccessNotify
            - Key: onFail
              RefValue: FailureNotify
        - Id: SuccessNotify
          Name: SuccessNotify
          Fields:
            - Key: type
              StringValue: SnsAlarm
            - Key: topicArn
              StringValue: "#{myTopicArn}"
            - Key: subject
              StringValue: "[Info] MongoDB Backup Succeeded"
            - Key: message
              StringValue: |
                scheduledStartTime: "#{node.@scheduledStartTime}"
                actualStartTime: "#{node.@actualStartTime}"
                actualEndTime: "#{node.@actualEndTime}"
                hostname: "#{node.hostname}"
        - Id: FailureNotify
          Name: FailureNotify
          Fields:
            - Key: type
              StringValue: SnsAlarm
            - Key: topicArn
              StringValue: "#{myTopicArn}"
            - Key: subject
              StringValue: "[Alart] MongoDB Backup Failed"
            - Key: message
              StringValue: |
                scheduledStartTime: "#{node.@scheduledStartTime}"
                actualStartTime: "#{node.@actualStartTime}"
                actualEndTime: "#{node.@actualEndTime}"
                hostname: "#{node.hostname}"
      ParameterObjects:
        - Id: myInstanceType
          Attributes:
            - Key: type
              StringValue: String
            - Key: default
              StringValue: t2.nano
            - Key: description
              StringValue: Instance type for performing the restore.
            - Key: allowedValues
              StringValue: t2.nano
            - Key: allowedValues
              StringValue: t2.micro
            - Key: allowedValues
              StringValue: m3.medium
            - Key: allowedValues
              StringValue: m3.large
            - Key: allowedValues
              StringValue: m3.xlarge
            - Key: allowedValues
              StringValue: m3.2xlarge
            - Key: allowedValues
              StringValue: c3.large
            - Key: allowedValues
              StringValue: c3.xlarge
            - Key: allowedValues
              StringValue: c3.2xlarge
            - Key: allowedValues
              StringValue: c3.4xlarge
            - Key: allowedValues
              StringValue: c3.8xlarge
        - Id: myExecutionTimeout
          Attributes:
            - Key: type
              StringValue: String
            - Key: default
              StringValue: "360 Minutes"
            - Key: description
              StringValue: Terminate the resource after this period.
        - Id: myStartDateTime
          Attributes:
            - Key: type
              StringValue: String
            - Key: default
              StringValue: "2017-12-01T00:00:00"
            - Key: description
              StringValue: Start at date/time.
        - Id: mySubnetId
          Attributes:
            - Key: type
              StringValue: String
            - Key: default
              StringValue: subnet-1234abcd
            - Key: description
              StringValue: VPC subnet for your restoration EC2 instance (ideally the same subnet used for the backup MongoDB).
        - Id: mySecurityGroupId
          Attributes:
            - Key: type
              StringValue: String
            - Key: default
              StringValue: sg-1111111b
            - Key: description
              StringValue: Security group that can connect to the Production/Backup MongoDB.
        - Id: myMongoHost
          Attributes:
            - Key: type
              StringValue: String
            - Key: default
              StringValue: backup-fs-12345678
            - Key: description
              StringValue: Name for the directory that already contains your backups.
        - Id: myDBuser
          Attributes:
            - Key: type
              StringValue: String
            - Key: default
              StringValue: root
            - Key: description
              StringValue: DB username.
        - Id: myDBpassword
          Attributes:
            - Key: type
              StringValue: String
            - Key: default
              StringValue: abc
            - Key: description
              StringValue: DB password.
        - Id: myDBname
          Attributes:
            - Key: type
              StringValue: String
            - Key: default
              StringValue: none
            - Key: description
              StringValue: DB name.
        - Id: myDBcollection
          Attributes:
            - Key: type
              StringValue: String
            - Key: default
              StringValue: none
            - Key: description
              StringValue: DB colllection.
        - Id: myDBquery
          Attributes:
            - Key: type
              StringValue: String
            - Key: default
              StringValue: none
            - Key: description
              StringValue: DB query.
        - Id: myDBatlasShared
          Attributes:
            - Key: type
              StringValue: String
            - Key: default
              StringValue: none
            - Key: description
              StringValue: DB atlas-shared.
        - Id: myDBatlasReplicaset
          Attributes:
            - Key: type
              StringValue: String
            - Key: default
              StringValue: none
            - Key: description
              StringValue: DB atlas-replicaset.
        - Id: myRegion
          Attributes:
            - Key: type
              StringValue: String
            - Key: default
              StringValue: GMT
            - Key: description
              StringValue: TimeZone
        - Id: myS3BackupsBucket
          Attributes:
            - Key: type
              StringValue: String
            - Key: default
              StringValue: s3://efs-backups
            - Key: description
              StringValue: S3 Backup Bucket
        - Id: myImageId
          Attributes:
            - Key: type
              StringValue: String
            - Key: default
              StringValue: ami-12345678
            - Key: description
              StringValue: AMI ID for the EC2 instance.
        - Id: myS3LogBucket
          Attributes:
            - Key: type
              StringValue: String
            - Key: default
              StringValue: s3://my-s3-log-bucket
            - Key: description
              StringValue: S3 Log Bucket
        - Id: myDataPipelineResourceRole
          Attributes:
            - Key: type
              StringValue: String
            - Key: default
              StringValue: DataPipelineDefaultResourceRole
            - Key: description
              StringValue: DataPipeline Resource Role
        - Id: myDataPipelineRole
          Attributes:
            - Key: type
              StringValue: String
            - Key: default
              StringValue: DataPipelineDefaultRole
            - Key: description
              StringValue: DataPipeline Role
        - Id: myTopicArn
          Attributes:
            - Key: type
              StringValue: String
            - Key: default
              StringValue: arn:aws:sns:hoge
            - Key: description
              StringValue: Topic ARN
        - Id: myKeyPair
          Attributes:
            - Key: type
              StringValue: String
            - Key: default
              StringValue: my-key
            - Key: description
              StringValue: Key Pair
        - Id: myPeriod
          Attributes:
            - Key: type
              StringValue: String
            - Key: default
              StringValue: "1 hours"
            - Key: description
              StringValue: How often the pipeline should run
      ParameterValues:
        - Id: myInstanceType
          StringValue: !Ref myInstanceType
        - Id: myExecutionTimeout
          StringValue: !Ref myExecutionTimeout
        - Id: mySubnetId
          StringValue: !Ref mySubnetId
        - Id: mySecurityGroupId
          StringValue: !Ref mySecurityGroupId
        - Id: myMongoHost
          StringValue: !Ref myMongoHost
        - Id: myDBuser
          StringValue: !Ref myDBuser
        - Id: myDBpassword
          StringValue: !Ref myDBpassword
        - Id: myDBname
          StringValue: !Ref myDBname
        - Id: myDBcollection
          StringValue: !Ref myDBcollection
        - Id: myDBquery
          StringValue: !Ref myDBquery
        - Id: myDBatlasShared
          StringValue: !Ref myDBatlasShared
        - Id: myDBatlasReplicaset
          StringValue: !Ref myDBatlasReplicaset
        - Id: myRegion
          StringValue: !Ref myRegion
        - Id: myS3BackupsBucket
          StringValue: !Ref myS3BackupsBucket
        - Id: myImageId
          StringValue: !Ref myImageId
        - Id: myS3LogBucket
          StringValue: !Sub s3://${myS3LogBucket}
        - Id: myDataPipelineResourceRole
          StringValue: !Ref myDataPipelineResourceRole
        - Id: myDataPipelineRole
          StringValue: !Ref myDataPipelineRole
        - Id: myTopicArn
          StringValue: !Ref myTopicArn
        - Id: myKeyPair
          StringValue: !Ref myKeyPair
        - Id: myStartDateTime
          StringValue: !Ref myStartDateTime
        - Id: myPeriod
          StringValue: !Ref myPeriod

Outputs:
  DataPipelineId:
    Value: !Ref DataPipelineMongoBackup
