---
AWSTemplateFormatVersion: 2010-09-09
Description: DataPipeline EFS Backup SNS Template

Parameters:
  Email:
    Type: String

Conditions:
  SubscribeEmail: !Not [!Equals [ !Ref Email, ""]]

Resources:
  Topic:
    Type: AWS::SNS::Topic

  EmailSubscription:
    Condition: SubscribeEmail
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref Topic
      Protocol: email
      Endpoint: !Ref Email

Outputs:
  TopicArn:
    Value: !Ref Topic
